steps:
  - id: sonar_scan
    name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: sh
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.projectKey=SonarCloudTest \
          -Dsonar.organization=yousaikei \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$_SONARTOKEN \
          -Dsonar.sources=.
