steps:
  # 1️⃣ SonarCloud 扫描
  - id: sonar_scan
    name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: sh
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.projectKey=SonarCloudTest \
          -Dsonar.organization=yousaikei \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

  # 2️⃣ 发 GitHub PR 评论
  - id: sonar_comment
    name: 'alpine:3.18'
    entrypoint: sh
    args:
      - '-c'
      - |
        set -e
        SONAR_PROJECT_KEY=SonarCloudTest
        REPO_FULL_NAME=yousaikei/SonarCloudTest
        COMMIT_SHA=$SHORT_SHA

        # 获取 Quality Gate 状态
        STATUS=$(curl -s -u $SONAR_TOKEN: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | jq -r '.projectStatus.status')

        # PR Number（PoC可手动填写或从 webhook payload 获取）
        PR_NUMBER=1

        # 发评论
        curl -s -X POST -H "Authorization: token $GITHUB_PAT" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO_FULL_NAME/issues/$PR_NUMBER/comments \
          -d "{\"body\":\"🔍 SonarCloud Quality Gate: **$STATUS** → [See Report](https://sonarcloud.io/dashboard?id=$SONAR_PROJECT_KEY)\"}"

substitutions:
  _SONAR_TOKEN: $SONAR_TOKEN
  _GITHUB_PAT: $GITHUB_PAT

