steps:
  - id: sonar_scan
    name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: sh
    env:
      - 'SONARTOKEN'   # 直接引用 Cloud Build 环境变量
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.projectKey=SonarCloudTest \
          -Dsonar.organization=yousaikei \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONARTOKEN

  - id: sonar_comment
    name: 'alpine:3.18'
    entrypoint: sh
    env:
      - 'GITHUBPAT'
      - 'SONARTOKEN'
    args:
      - '-c'
      - |
        STATUS=$(curl -s -u $SONARTOKEN: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=SonarCloudTest" | jq -r '.projectStatus.status')

        PR_NUMBER=1
        REPO_FULL_NAME=yousaikei/SonarCloudTest

        curl -s -X POST -H "Authorization: token $GITHUBPAT" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO_FULL_NAME/issues/$PR_NUMBER/comments \
          -d "{\"body\":\"🔍 SonarCloud Quality Gate: **$STATUS** → [See Report](https://sonarcloud.io/dashboard?id=SonarCloudTest)\"}"


