# 最简方案：先修改权限再运行
steps:
  # 步骤 1: 运行 Python HelloWorld
  - name: 'python:3.9-slim'
    entrypoint: 'python'
    args: ['main.py']
    id: 'run-hello-world'

  # 步骤 2: 修改权限并运行 SonarCloud 扫描
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        chmod 777 /workspace
        sonar-scanner \
          -Dsonar.projectKey=SonarCloudTest \
          -Dsonar.organization=yousaikei \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$_SONARTOKEN \
          -Dsonar.sources=.
    id: 'sonar-scan'
    dependsOn: ['run-hello-world']

# 可选: 设置超时
timeout: '600s'
